### ISSUE TITLE
How does one compile this tool for use? 

### ISSUE THREAD

**Issue by NicholasJohnson9149** [ValeryToda/DataVisualizer#2]
I can't compile this program, any recommendations?

**Comment by ValeryToda** [comment]
Just download the files and open the project with Qt Creator and build the project. There are no dependencies. If you are using a Mac just download the file DataVisualizer.app and you are good to go. Hope it helps.

**Comment by ValeryToda** [comment]
Here are the steps to help you build the project:

1. Download and install the latest Qt version from [here](https://info.qt.io/download-qt-for-application-development) 
2. Download the project files from [here](https://github.com/ValeryToda/DataVisualizer.git). 
3. Open the project with the application Qt Creator and build it.
